### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by AlexaTanner** [STAT545-UBC/Discussion-Internal#1]

**Comment by JasmineLib** [comment]
Hey @AlexaTanner
My name is Jasmine, looking forward to this semester!

**Comment by lsloboda** [comment]
Hi @JasmineLib 
I'm Laura, nice to meet you!

**Comment by RyanGao67** [comment]
Hi @AlexaTanner  
My name is Tian
Nice to meet you

**Comment by Caroline-Seip** [comment]
Hi @RyanGao67 
My name is Caroline, nice to meet you!

**Comment by Sukeysun** [comment]
Hi @AlexaTanner 
My name is Sukey, nice to meet you!

**Comment by ecool50** [comment]
hi @RyanGao67 
My name is Elijah, nice to meet you.

**Comment by jondeuce** [comment]
Hi, my name is Jon Doucette. I'm studying MRI Physics, currently in my second year of my Master's. Nice to meet you, @ecool50.

**Comment by ecool50** [comment]
To install bash on window 10: https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by figalit** [comment]
Hi, this is Figali.
