### ISSUE TITLE
Unable to push to GitHub from local

### ISSUE THREAD

**Issue by bassamjaved** [STAT545-UBC/Discussion-Internal#10]
Anyone else get this error when trying to push commits from your local to GitHub:

**error: unable to read askpass response from 'rpostback-askpass'
fatal: could not read Username for 'https://github.com': Device not configured**

I am able to stage and commit, but no luck on pushes.

**Comment by YuHsiangLo** [comment]
I think this post might be useful: https://github.com/STAT545-UBC/Discussion/issues/93

**Comment by bassamjaved** [comment]
I followed the tutorial on happygitwithr.com to cache credentials and a
lock icon appears whenever I enter my username. Pressing enter again, I get
an authentication error.

**Comment by malvikamitra1** [comment]
I am facing the same problem

**Comment by YuHsiangLo** [comment]
Oh that means you need type in your password at this point. While you're typing, nothing will show up on Terminal but it's still getting recorded.

**Comment by bassamjaved** [comment]
Thanks @YuHsiangLo . That worked!
