### ISSUE TITLE
Peer review 10

### ISSUE THREAD

**Issue by g-ziyan** [STAT545-UBC/Discussion-Internal#100]
Hey @STAT545-UBC/2018_teaching_team,

Just wondering would the peer review 10 be posted? Since assignment 10 is optional, for the students who need to do peer review10, could we randomly pick two assignments to review and link them on canvas?

Thanks!

**Comment by ChadFibke** [comment]
Hey @g-ziyan,

I do not think the peer review will be posted, so you should randomly choose 2 assignments to review. Yes, please append a link to your canvas submission.

**Comment by g-ziyan** [comment]
Thanks for your reply. Good to know that. Could you open a submission for peer review 10 in canvas?

**Comment by ChadFibke** [comment]
Hey @g-ziyan,

I do not have permission on canvas to do that, but @vincenzocoia, or @hsmohammed do! If there is no submission to canvas, but there is a comment on github, we will find it and you will receive marks. 

Chad

**Comment by rning-wu** [comment]
@ChadFibke So there is no need for us to link our peer reviews?

Thanks

**Comment by ChadFibke** [comment]
Hey @rning-wu,

Nope! Only a few students have completed the assignment, so it will be very easy to manage and document who commented on what. 

Cheers
