### ISSUE TITLE
Not able to install package for homework 1

### ISSUE THREAD

**Issue by couBC** [STAT545-UBC/Discussion-Internal#11]
I am getting this message when I try to open the package 'iris' in RStudio version control which doesn't make sense because I know I have that dataset. Any suggestions?

> install.packages('iris')
Warning in install.packages :
  package ‘iris’ is not available (for R version 3.3.3)
> 

> knitr::opts_chunk$set(echo = TRUE)
> library('iris')
Error in library("iris") : there is no package called ‘iris’

**Comment by ericjsanders** [comment]
Iris comes preloaded into R, so you don't actually have to install it. Try running `data(iris)`
, then when you run `summary(iris)` as a test, it should report on the data set.

If it still doesn't work, try running `library(datasets)` first to check that R is ready to access preloaded datasets.

**Comment by ShuxianFan** [comment]
try 
library(datasets)
data(iris)

**Comment by couBC** [comment]
Yay Thank you Eric and Shuxian! That worked! 👍
