### ISSUE TITLE
unable to clone and push from local to GitHub

### ISSUE THREAD

**Issue by malvikamitra1** [STAT545-UBC/Discussion-Internal#12]
Facing these problems when trying to Push from Local to GitHub and Clone from GitHub to Local
 
>>> git push origin refs/heads/master
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/amitra/Desktop/RStudio 2.app/Contents/MacOS/rpostback
  Reason: image not found
/Users/amitra/Desktop/RStudio 2.app/Contents/MacOS/postback/rpostback-askpass: line 20: 20901 Abort trap: 6           "$RS_RPOSTBACK_PATH" askpass "$@"
error: unable to read askpass response from 'rpostback-askpass'
fatal: could not read Username for 'https://github.com': Device not configured

Cloning into 'hw01-malvikamitra1'...
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rasiimwe** [comment]
@malvikamitra1 

It would be more helpful to provide some detail on the method used for cloning, but please see: https://github.com/docker-library/golang/issues/148  in case you find it helpful. Also, assuming git was well configured following: http://happygitwithr.com/push-pull-github.html, the directory you are cloning shouldn't be empty.
