### ISSUE TITLE
Posted: Homework 02 and Peer Review 01

### ISSUE THREAD

**Issue by vincenzocoia** [STAT545-UBC/Discussion-Internal#13]
@STAT545-UBC/2018_students cc @STAT545-UBC/2018_teaching_team 

[Homework 02](http://stat545.com/Classroom/assignments/hw02/hw02.html) has been posted.

[Peer Review 01](http://stat545.com/Classroom/assignments/hw01/pr01.html) has been posted.

**Comment by vincenzocoia** [comment]
Sorry for the delay, but the link to create your Homework 02 repo is now available on canvas.

**Comment by MielleM** [comment]
How do we submit the peer reviews? I don't see anything under the "How to submit a peer review" section of the [assignments](http://stat545.com/Classroom/assignments/) page. 

Thanks!

**Comment by cbnicolau** [comment]
I think you are supposed to submit it as an "issue" in the student's repo

**Comment by vincenzocoia** [comment]
> How do we submit the peer reviews? I don't see anything under the "How to submit a peer review" section of the assignments page.

Sorry about that, I fixed the missing section.
