### ISSUE TITLE
hw2 - datatype from typeof() class() mode() 

### ISSUE THREAD

**Issue by ShuxianFan** [STAT545-UBC/Discussion-Internal#15]
`class(gapminder)`

[1] "tbl_df"     "tbl"        "data.frame"

`typeof(gapminder::gapminder)`

[1] "list"`

output from using class()

 country   continent      year      lifeExp      pop     gdpPercap 
 "factor"  "factor".    "integer" "numeric" "integer" "numeric" 

output from using typeof()

country   continent      year   lifeExp       pop gdpPercap 
"integer" "integer" "integer"  "double" "integer"  "double" 

I was trying out the hw2 and I am not sure if I answered the questions being asked.
The `class()` and `typeof()` give different outputs and I am having difficulty interpreting them.

From the R document I found that:
If the object does not have a class attribute, it has an implicit class, notably "matrix", "array", "function" or "numeric" or the result of typeof(x)(which is similar to mode(x)).

 I am wondering why in this case the country variable in the gapminder is "integer" by `typeof()`(Intuitively it should be a factor).

**Comment by glenn-mcguinness** [comment]
The typeof function only provides the type the object internal to R.  This page describes typeof [typeof](https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/typeof). This page lists all of the internal R types that it can return, which does not include factor.  An instance of a factor is stored as an integer.

**Comment by ShuxianFan** [comment]
@glenn-mcguinness Thank you!
