### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by glenn-mcguinness** [STAT545-UBC/Discussion-Internal#16]
In the marking rubric, the coding style section references a "coding manual". Where can we find the coding manual?

**Comment by vincenzocoia** [comment]
Good catch. We aren't being all that strict about it this time, but one manual you can follow is the [tidyverse R style guide](http://style.tidyverse.org/).

**Comment by glenn-mcguinness** [comment]
Thank you for providing the manual! Should we use this coding style guide for judging style in future peer reviews?

**Comment by vincenzocoia** [comment]
I do encourage the use of the tidyverse style guide. Conforming exactly to the guide is not necessary, but code should be made as "clean" and readable as realistically possible.

**Comment by glenn-mcguinness** [comment]
Ok, thanks! I will keep that in mind for my peer reviews.
