### ISSUE TITLE
Introduce yourself here!

### ISSUE THREAD

**Issue by vincenzocoia** [STAT545-UBC/Discussion-Internal#2]
Hi everyone! Please introduce yourself here.

**Comment by Bill1111** [comment]
Hi my name is William. I am in Health Economics. Looking forward to learning more about R in this course :)

**Comment by funkedavid82** [comment]
Hi, I am Jummy

**Comment by lsloboda** [comment]
Hi @funkedavid82 
I'm Laura, nice to meet you!

**Comment by Caroline-Seip** [comment]
@Bill1111 Hey William, my name is Caroline and I am in Forestry, nice to meet you!

**Comment by Ninadh** [comment]
Hi, this is Ninadh

@funkedavid82

**Comment by RyanGao67** [comment]
Hi @lsloboda 
I'm tian. nice tomeet you

**Comment by cbnicolau** [comment]
Hi, I'm Coni!
@Bill1111

**Comment by couBC** [comment]
Hello, I'm Christine. I'm in Nursing - @YuHsiangLo

**Comment by JennFerris** [comment]
Hi @Caroline-Seip Im Jenn!

**Comment by fjbasedow** [comment]
Hi @couBC, I'm Rike!

**Comment by zeeva85** [comment]
Hi @Caroline-Seip I am seeva

**Comment by alvin-q** [comment]
Hi @couBC, my name is Alvin. I'm a 3rd year MD/PhD student.

**Comment by shreeramsenthi** [comment]
Hey @lsloboda,
Nice to meet you all!

**Comment by Kate96** [comment]
Hi, I am Kate! I am in Oncology program :) @JennFerris

**Comment by zuhengxu** [comment]
hi, I'm David, nice to meet you! @jennybc

**Comment by zhamadeh** [comment]
Hi I'm Zeid.
@cbnicolau

**Comment by jkioke** [comment]
@alvin-q
Good morning!

**Comment by MaunishUBC** [comment]
Hey @Caroline-Seip 
I am Maunish

**Comment by rachlobay** [comment]
Hi @zhamadeh. My name is Rachel and I am in Statistics.

**Comment by ntjjmak** [comment]
@zuhengxu
My name is Nicole!
I am in MSc. Surgery.
:D

**Comment by aleurcelay** [comment]
Hi @zhamadeh I'm Alejandra :)

**Comment by ericjsanders** [comment]
@couBC Hi Christine! I'm Eric, I'm a second year Biostatistics student

**Comment by acheng-ubc** [comment]
Hello my name is Alex, I am in Experimental Medicine. Nice to meet everyone! 
@ericjsanders

**Comment by zjbthomas** [comment]
Hi @ntjjmak, nice to meet you.
My name is Thomas.

**Comment by schignel** [comment]
Hi @ericjsanders! I'm Steve in the Institute for Resources, Environment and Sustainability

**Comment by yavyx** [comment]
Hello @ntjjmak! My name is Javier and I'm in the Bioinformatics Master's program.

**Comment by glenn-mcguinness** [comment]
Hello @ericsanders, I'm Glenn and I'm in Statistics.

**Comment by JasmineLib** [comment]
Hey @aleurcelay

my name is Jasmine, I'm doing my masters in Biochemistry, looking forward to meeting you!

**Comment by conradtsang** [comment]
Hi @ericjsanders
I'm Conrad, from in medicine -- excited to meet you all this semester!

**Comment by slumnitz** [comment]
Hi  @zuhengxu my name is Stef. I am in Forestry. Nice to meet you all!

**Comment by xcct2012** [comment]
Zach Sherker, MSc Resources Environment and Sustainability investigating Pacific Great Blue Heron predation on outmigrating salmon smolts (juveniles exiting natal rivers and streams) @JennFarris

**Comment by rasiimwe** [comment]
Hi, My name is Rebecca Asiimwe. I am in the MSc. Bioinformatics Program. 

@aleurcelay

**Comment by iyaniwura** [comment]
Hi @jennybc

**Comment by huangjieying** [comment]
Hi I’m Jenny Huang @slumnitz

**Comment by bassamjaved** [comment]
@iyaniwura 
Hi, I'm Bassam

**Comment by lucymosquera** [comment]
Hello @iyaniwura! I'm starting a MSc in Biostatistics!

**Comment by alorentzian** [comment]
Hi @lucymosquera
I'm Amanda! I'm a PhD student in Cell Biology

**Comment by eaerh** [comment]
Hello @alorentzian, I'm Erik from Norway. Nice to meet you all!

**Comment by rning-wu** [comment]
Hi @vincenzocoia, I'm Ray, nice to meet you!

**Comment by HJMcSorley** [comment]
Hi! I'm Hannah, I'm a first year Master's student in EOAS, researching regional water supplies in Ecohydrology.

**Comment by AlexaTanner** [comment]
Hello @rning-wu Nice to meet you!

**Comment by 451error** [comment]
Hi @alorentzian I'm Tom, nice to meet you!

**Comment by j-schaub** [comment]
Hi @rning-wu I am Jessica, I'm starting an MSc. in Oceanography!

**Comment by curtis77** [comment]
Hi!

**Comment by garyzhubc** [comment]
Hi @AlexaTanner I'm Gary in MS Stat, Nice to meet you!

**Comment by YuHsiangLo** [comment]
Hi, @eaerh, I'm Roger. Nice to meet you!

**Comment by tsmith93** [comment]
Hi @curtis77 I'm Thomas, I'm the Institute for the Oceans and Fisheries.

**Comment by schignel** [comment]
Hi @garyzhubc, I'm Steve Chignell, in IRES!

**Comment by curtis77** [comment]
@rning-wu

**Comment by Sukeysun** [comment]
Hi, I'm Sukey and I'm in ECE !

**Comment by janehuang1647** [comment]
Hi I am Jane from EECE department

**Comment by MalcolmNSB** [comment]
Hi @MaunishUBC  I'm Malcolm, a PhD student in mathematics!

**Comment by divita95** [comment]
Hi @MalcolmNSB, i am Divita, an MEng student in the department of Chemical and Biological Eng. Nice to meet you.. :)

**Comment by CeciliaLe07** [comment]
HI every one, I'm Cecilia and I'm going to start the Master in Statistics :D

**Comment by ShuxianFan** [comment]
Hi everyone, sorry for the late comment.  I am Shuxian and I'm first year Master student in Stats.

**Comment by vetlebh** [comment]
Hi, @RetoSterchi! I'm Vetle, a norwegian guy studying Data Science, currently as a visiting student at UBC. Cheers!

**Comment by albina23** [comment]
Hi! I am Albina, MA Geography student working on political economy, financial geography.

**Comment by MielleM** [comment]
Hey, @albina23! Another geographer here, starting my MSc studying environmental health geography and GIS. Dropping by a bit late, but nice to meet you all :)

**Comment by g-ziyan** [comment]
Hi @MielleM, my name is Ziyan. I'm in the second year of the Master of Computer Engineering. Looking forward to meet you all and hoping I'm not the latest :)

**Comment by ErnestL91** [comment]
Hi there! I am Ernest, a second year student in Masters of Science in School Population Public Health. Nice to meet you all :) ;)

**Comment by MeiqiYu** [comment]
Hi @ErnestL91 , I am Meiqi from Electrical and Computer Engineering. Nice to meet you!

**Comment by liuyadong08** [comment]
HI, I am Yadong from Department of Lingstics. Nice to meet you!

**Comment by katiezinn** [comment]
Hello! I am Katie- doing my MSc in Zoology!

**Comment by liao02x** [comment]
Hello to all! This is Minzhi from ECE!

**Comment by seraphinearnold** [comment]
Hello @zeeva85, this is Seraphine.

**Comment by Irissq28** [comment]
Hi @seraphinearnold, this is Siqi from ECE department.
