### ISSUE TITLE
Installing tidyverse

### ISSUE THREAD

**Issue by iyaniwura** [STAT545-UBC/Discussion-Internal#20]
Hi Guys,

I have been trying to install the tidyverse package on my laptop and it has not be successful. Below is a screenshot of the error messages I got.

Does anyone has an idea of how to resolve this issue?

Thanks!

ERROR: configuration failed for package ‘xml2’
* removing ‘/home/iyaniwura/R/x86_64-pc-linux-gnu-library/3.2/xml2’
Warning in install.packages :
  installation of package ‘xml2’ had non-zero exit status
ERROR: dependencies ‘curl’, ‘openssl’ are not available for package ‘httr’
* removing ‘/home/iyaniwura/R/x86_64-pc-linux-gnu-library/3.2/httr’
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
ERROR: dependencies ‘xml2’, ‘httr’ are not available for package ‘rvest’
* removing ‘/home/iyaniwura/R/x86_64-pc-linux-gnu-library/3.2/rvest’
Warning in install.packages :
  installation of package ‘rvest’ had non-zero exit status
ERROR: dependencies ‘httr’, ‘rvest’, ‘xml2’ are not available for package ‘tidyverse’
* removing ‘/home/iyaniwura/R/x86_64-pc-linux-gnu-library/3.2/tidyverse’
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpPLaM9n/downloaded_packages’

**Comment by rning-wu** [comment]
I assume you're using ubuntu

I had that issue too, I fixed it by installing the missing packages: `sudo apt-get install xml2`

**Comment by zeeva85** [comment]
what system are you on ? 

`install.packages("xml2")` ?

**Comment by iyaniwura** [comment]
> I assume you're using ubuntu
> 
> I had that issue too, I fixed it by installing the missing packages: `sudo apt-get install xml2`

@rning-wu I am using Ubuntu. I tried this and the error still persist. Thanks for your help!

**Comment by iyaniwura** [comment]
> what system are you on ?
> 
> `install.packages("xml2")` ?

@zeeva85 I have tried this too, no success! It still gives the same error message. Thanks!

**Comment by zeeva85** [comment]
I think its what @rning-wu said in the shell type 

`sudo apt-get update`

then 

`sudo apt-get install libxml2-dev`

if it still fails maybe try..

`sudo apt-get install libxml2-dev`

**Comment by iyaniwura** [comment]
> I think its what @rning-wu said, and I assume you typed in the shell and not the r console.
> 
> `sudo apt-get update`
> 
> then
> 
> `sudo apt-get install libxml2-dev`
> 
> if it still fails maybe try..
> 
> `sudo apt-get install r-cran-xml`
> or maybe
> 
> `sudo apt-get install r-cran-xml2`
> 
> not so sure which is the correct one, give it a go and see. hopefully it sorts it out

@zeeva85, I have installed xml2 now but it did not install tidyverse still. Here is the error message now:

ERROR: configuration failed for package ‘openssl’
* removing ‘/home/iyaniwura/R/x86_64-pc-linux-gnu-library/3.2/openssl’
Warning in install.packages :
  installation of package ‘openssl’ had non-zero exit status
ERROR: dependencies ‘curl’, ‘openssl’ are not available for package ‘httr’
* removing ‘/home/iyaniwura/R/x86_64-pc-linux-gnu-library/3.2/httr’
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
ERROR: dependency ‘httr’ is not available for package ‘rvest’
* removing ‘/home/iyaniwura/R/x86_64-pc-linux-gnu-library/3.2/rvest’
Warning in install.packages :
  installation of package ‘rvest’ had non-zero exit status
ERROR: dependencies ‘httr’, ‘rvest’ are not available for package ‘tidyverse’
* removing ‘/home/iyaniwura/R/x86_64-pc-linux-gnu-library/3.2/tidyverse’
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

**Comment by zeeva85** [comment]
😆
 maybe try this 

`install.packages("tidyverse", dependencies=TRUE)`

if not I think you need to manually install the dependencies, they should be a way to install tidy verse and get all the dependencies

**Comment by glenn-mcguinness** [comment]
I also had this problem. I fixed it by installing the following packages
```
sudo apt-get update && sudo apt-get install libcurl4-openssl-dev && sudo apt-get install openssl
```
If you keep getting an error, try googling the package name and try installing it using sudo apt-get.

**Comment by rasiimwe** [comment]
You could also try:

**sudo apt-get install libcurl4-openssl-dev libssl-dev** 

and then install tidyverse they default way.

It could also help to run some updates and upgrades

This could be a good question for the external forum as well

**Comment by iyaniwura** [comment]
It has been installed now, here is what I did:

First I used
~~~
sudo apt-get install libxml2-dev
~~~

to install xml2 package, then used 

~~~
sudo apt-get install libcurl4-openssl-dev libssl-dev
~~~
to install openssl and curl.

Thank to everyone for your assistance!
