### ISSUE TITLE
Peer Review hw01

### ISSUE THREAD

**Issue by aschmalor** [STAT545-UBC/Discussion-Internal#21]
Hi guys,

I'm not sure how to create a proper peer review that is coded through R (that includes tables, emojis etc.).
Do we just create a new issue and then put the review directly in there or do we upload/link a file that is written in R? And if so, how do we do that?

Thanks!

**Comment by rachlobay** [comment]
I think it is simply to create the new issue and put the review directly in there. But let's double check with @vincenzocoia.

**Comment by ChadFibke** [comment]
@rachlobay is correct. Head to the repo you'd like to review. Once in the repo click on the issues tab > new issue, and then you can craft your review in there... no pulling, committing, or pushing! I believe all the rmd syntax still works in the comments you leave, so you can give your new friends a :thumbsup:.

**Comment by aschmalor** [comment]
Thanks!
