### ISSUE TITLE
Hw02?

### ISSUE THREAD

**Issue by ntjjmak** [STAT545-UBC/Discussion-Internal#22]
How do we create a new repository for the second assignment? I see some of you already have one---mind sharing how you created it??

Many thanks,

Nicole

**Comment by alvin-q** [comment]
Hey,
It's the same as last time. Login to canvas, click the 2nd homework link. and there's a button that automatically creates one.

**Comment by huangjieying** [comment]
Like we did for first assignment, there is a link on Canvas

**Comment by sherrie9** [comment]
Don't create a new repository for each homework, simply add a new folder for hw 2 in your already existing repo.

**Comment by vincenzocoia** [comment]
Sorry for the confusion, everyone. You can create a new repo for your homework by finding the link on Canvas.

In previous years, we had only one homework repository to put all the homework. My apologies if this is confusing -- I hope to converge to a course framework in the near future where all these things are clear.
