### ISSUE TITLE
What to do when a student repository for peer review doesn't exist

### ISSUE THREAD

**Issue by MalcolmNSB** [STAT545-UBC/Discussion-Internal#23]
I don't think this was asked previously, but apologies if I missed it.

What should we do if we get a _404 does not exist_ error page for the student repository who we are supposed to review?

@vincenzocoia

**Comment by Kate96** [comment]
Hi @MalcolmNSB!

I had the same problem and received the following reply:

"Reviewer should randomly choose another student and review their work. Reviewer should also indicate this change on canvas, and provide a link to their reviews (as usual)."

Hope this helps!

**Comment by MalcolmNSB** [comment]
Thanks @Kate96!

**Comment by vincenzocoia** [comment]
Thanks @Kate96 ! That's correct. I added that piece of info on the (new) [peer review page](http://stat545.com/Classroom/assignments/peer-review.html).
