### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by malvikamitra1** [STAT545-UBC/Discussion-Internal#24]
unable to access the person's homework repository that I have to review.
https://github.com/STAT545-UBC-students/hw01-Greenhan

Can't find the link to the respective homework even on the main webpage with the links to all the homeworks
https://github.com/STAT545-UBC-students

**Comment by hsmohammed** [comment]
You should randomly choose another student and review their work. You should also indicate this change on canvas, and provide a link to your reviews (as usual).

**Comment by malvikamitra1** [comment]
okay
Thank you
