### ISSUE TITLE
Creating a new project

### ISSUE THREAD

**Issue by alorentzian** [STAT545-UBC/Discussion-Internal#25]
I'm having this error when I try to create a new project for my hw02 repository. I've created projects before without any issue. Does anyone know what I could be doing wrong?

![image](https://user-images.githubusercontent.com/42976523/46027913-fa84a780-c0a3-11e8-8636-03f0f361dbb8.png)

Thanks!

**Comment by Caroline-Seip** [comment]
I'm guessing your file name is either too long, or contains spaces or special characters? Try just calling it something very simple and see if that works
