### ISSUE TITLE
Posted: Homework 03 and Homework 04

### ISSUE THREAD

**Issue by hsmohammed** [STAT545-UBC/Discussion-Internal#27]
@STAT545-UBC/2018_students cc @STAT545-UBC/2018_teaching_team

[Homework 03](http://stat545.com/Classroom/assignments/hw03/hw03.html) has been posted.
[Homework 03](http://stat545.com/Classroom/assignments/hw04/hw04.html) has been posted.

**Comment by rasiimwe** [comment]
@hsmohammed 

There's a typo on [canvas](https://github.com/rasiimwe/Misc/blob/master/Screen%20Shot%202018-09-26%20at%208.18.03%20PM.png) as well.
