### ISSUE TITLE
Posted: Homework 02 peer review

### ISSUE THREAD

**Issue by hsmohammed** [STAT545-UBC/Discussion-Internal#28]
@STAT545-UBC/2018_students cc @STAT545-UBC/2018_teaching_team

[Peer review for homework 02](http://stat545.com/Classroom/assignments/hw02/pr02.html) has been posted.

**Comment by rachlobay** [comment]
Hi @STAT545-UBC/2018_teaching_team It looks like the [Peer review links for homework 2](http://stat545.com/Classroom/assignments/hw02/pr02.html) are to the homework 1 repo for students. Maybe that is just showing up like that for me... but please have a look at that.

**Comment by hsmohammed** [comment]
That was fixed. Thanks for pointing that out.
