### ISSUE TITLE
Homework2

### ISSUE THREAD

**Issue by funkedavid82** [STAT545-UBC/Discussion-Internal#31]
@vincenzocoia 
I submitted my homework2 on github yesterday but forgot to submit a reflection, I then submitted a reflection a few minutes ago. Will this be considered as late submission please?

**Comment by vincenzocoia** [comment]
No, your reflection is for us to have context on your submission. The grade you receive will be based on your submission as of the deadline, even if there's stuff added afterwards.

**Comment by funkedavid82** [comment]
> No, your reflection is for us to have context on your submission. The grade you receive will be based on your submission as of the deadline, even if there's stuff added afterwards.

Great! Thanks for letting me know.

**Comment by funkedavid82** [comment]
@ChadFibke @vincenzocoia 
Hi Chad,
Could you please explain why my grade  for homework2 was reduced by 50%? I asked this question before in this issue that I submitted the reflection after the deadline but my last commit on github (main submission) was before the deadline. I also need more feedback on my main grade before the 50% reduction, because I felt I did all that was required and even did more. Could you please look into my homework2 again and provide necessary/helpful feedback?

**Comment by funkedavid82** [comment]
@ChadFibke 
Yes, I submitted the reflection late but not the homework on github. The reflection was meant to explain how my homework2 was submitted, the challenges encountered during submission and so on. But no single file in my repo was changed past the due date. Could you please check my submission on github again and see if the last commit was after the due date because I uploaded figures on Tuesday night (Sept. 25, at around 8:30pm) and didn't change anything after the deadline. I think it will be fear if you can always go with the date on github and not on canvas since canvas is just for reflection according to @vincenzocoia. I am sorry if I wasn't clear enough but could you adjust my grade accordingly on canvas please?

**Comment by ChadFibke** [comment]
Hey Jummy,

My apologies I mixed up the assignment dates. Your grade will be updated ASAP.

Chad
