### ISSUE TITLE
HW02 grade

### ISSUE THREAD

**Issue by Kate96** [STAT545-UBC/Discussion-Internal#37]
I was wondering if the grades for HW02 are not posted yet? I don't seem to have the assignment graded on Canvas, but I do have the TA comments as an issue, so I wanted to double check. 

@STAT545-UBC/2018_teaching_team

**Comment by ChadFibke** [comment]
Hey @Kate96,

HW02 marks are on their way. Generally speaking, you should have a mark back a week after you have submitted an assignment. 

Chad

**Comment by Kate96** [comment]
I see, thanks @ChadFibke!
