### ISSUE TITLE
HW02 grade revised

### ISSUE THREAD

**Issue by Rashedul** [STAT545-UBC/Discussion-Internal#40]
@2018_students,

Today I updated the grades for hw02. I graded the students whose home work I commented on. 

Please let me know if you did not receive any update.

Thanks!
Rashedul

**Comment by MaunishUBC** [comment]
Hi Rashedul, 

Just realized that I didn't get feedback and a grade on HW02. 
Can you please look into this whenever you have a chance.

Cheers,
Maunish

**Comment by ChadFibke** [comment]
Hey @MaunishUBC ,

Your grades should now be up to date on canvas. @hsmohammed was responsible for reviewing your homework 1.

**Comment by ChadFibke** [comment]
Sorry, **homework 2**

**Comment by hsmohammed** [comment]
Hi Maunish,

I just gave you feedback on your homework. Sorry for the late feedback.

Thanks..

**Comment by aleurcelay** [comment]
Hi @hsmohammed I don't have any feedback on my homework 3 but I do have a grade on Canvas. I think you graded my homework :). Could you check please?

Thank you!

**Comment by zjbthomas** [comment]
Hi @hsmohammed , I post a reply to your comment on my homework 3 ([here](https://github.com/STAT545-UBC-students/hw03-zjbthomas/issues/2)), could you please have a look? Thank you!
