### ISSUE TITLE
Question about office hour on Thanksgiving 

### ISSUE THREAD

**Issue by rachlobay** [STAT545-UBC/Discussion-Internal#41]
Hello @STAT545-UBC/2018_teaching_team,

I have checked on the [website](http://stat545.com/Classroom/) and it is listed that there is an office hour on Thanksgiving (Monday Oct. 8) from 11:00 - 12:00 in ESB 3174. I just wanted to double check that there will be an office hour on that day and that the ESB building will be not locked on the holiday?

**Comment by Rashedul** [comment]
Good point @rachlobay, thanks!

I think we will not have access to the room ESB 3174, since the reception will probably be closed on Monday.

@sherrie9 and @vincenzocoia , any comments?

**Comment by sherrie9** [comment]
I don't think there should be an office hour either.

**Comment by rachlobay** [comment]
Ok. Thank you for letting me know.

**Comment by vincenzocoia** [comment]
My apologies! I did not intend for there to be an office hour on Thanksgiving Monday. Glad that the intended solution was arrived at 😄
