### ISSUE TITLE
TROUBLE SUBMITTING ASSIGNMENT 5

### ISSUE THREAD

**Issue by janehuang1647** [STAT545-UBC/Discussion-Internal#44]
Hi Proferssion @vincenzocoia 

I have realized that there is no submission button in my canvas page for assignment 5 as shown below, how can I get this fixed?

![assignment 5](https://user-images.githubusercontent.com/40306764/46913067-ea414900-cf3a-11e8-85ee-d6e950a63554.JPG)

**Comment by rachlobay** [comment]
I second that. I don't see a submission button on my HW05 canvas page either... I think it is likely that the rest of the class probably has that issue too.

**Comment by hsmohammed** [comment]
@janehuang1647 @rachlobay I fixed that. Please check now.

**Comment by rachlobay** [comment]
@hsmohammed I checked. I can see the button now. Thanks :thumbsup:
