### ISSUE TITLE
Peer Review 3 typo?

### ISSUE THREAD

**Issue by schignel** [STAT545-UBC/Discussion-Internal#45]
Hi @STAT545-UBC/2018_teaching_team and class, 

I think there is a mistake on the title of the [Peer Review 04](http://stat545.com/Classroom/assignments/hw04/pr04.html) assignment page. 

The title for the page is currently "Peer Review 03" which I think should be "Peer Review 04". Just thought I'd mention in case it caused any confusion for people submitting their reviews tonight!

**Comment by MielleM** [comment]
I thought the due date for Assignment 5 was intentional? It seems like we're supposed to apply some of the lecture tomorrow (Tuesday) to the assignment. 

If that's not the case, and it's supposed to be due tomorrow, hopefully the 19th as a deadline will still be honored!

**Comment by tsmith93** [comment]
I am pretty sure the deadline is the 19th! I think the typo was having it stated as Tuesday the 19th as opposed to Friday the 19th.

**Comment by zeeva85** [comment]
I think it is 19th October, I saw that typo only yesterday was confused as well, and checked on canvas. It says 19th October on canvas as well, so I assume its 19th October 11.59 pm.

**Comment by aleurcelay** [comment]
I am also confused about the due date for assignment 5. Can you please clarify @vincenzocoia? :)

**Comment by hsmohammed** [comment]
I confirm that the deadline for assignment 5 is October 19. The error on the peer review page was fixed. Thanks!

**Comment by aleurcelay** [comment]
Thank you, @hsmohammed!

**Comment by Caroline-Seip** [comment]
Did anybody else find it confusing how it says "No need to submit anything here" on the peer review pages on Canvas? I'm not sure what that's supposed to mean, but I took this to mean that nothing needs to be submitted, so I didn't submit the links to my issues on the last peer review

**Comment by ericjsanders** [comment]
@Caroline-Seip I believe that it was just saying that it wasn't 100% necessary to attach the links. In the peer review part of the course website it says "it would be useful for you to submit a link to the two reviews you left; do so on the UBC Canvas page for the peer review. We will be putting your grades there."

I think this is just saying that it's optional, which is why it says there's "no need" on the assignment page.

**Comment by ChadFibke** [comment]
@Caroline-Seip,

You do not need to submit links to your peer reviews, but it is a great back up!  When  I go to input everyones peer review grade and see a 0% or 50% I will double check your submission links to see if either one of the TA's could't find your review, or my script has not properly matched  a student to their grade. If you do not submit the links, there is no safety net, and I am unable to correct any mistakes. Hope this helps.

Chad

**Comment by Caroline-Seip** [comment]
Ah ok thanks @ChadFibke I submitted the links to peer review 03 now. Maybe Canvas should just be updated to say "Please submit links to your peer reviews". 

Thanks!

**Comment by ChadFibke** [comment]
There is a comment about that [under the logistics section](http://stat545.com/Classroom/assignments/peer-review.html), but for next time we can certainly look into adding that onto canvas!
