### ISSUE TITLE
Thanks for a great course!

### ISSUE THREAD

**Issue by vetlebh** [STAT545-UBC/Discussion-Internal#47]
Huge thanks to both Vincenzo and the TA's. I have had a lot of fun and learned loads. And now I have also contributed to the discussion ;)

**Comment by eaerh** [comment]
I second this. Fun course!

**Comment by j-schaub** [comment]
I agree, this course was very informative and I can't wait for 547!

**Comment by xcct2012** [comment]
wonderful course!

**Comment by rachlobay** [comment]
Definitely 👍.  This course has been fun and practical. I think it will be easy to apply the knowledge from this course to our own work and research.

**Comment by schignel** [comment]
Yes, thanks very much to @STAT545-UBC/2018_teaching_team. This course was exactly what I needed, and I'm looking forward to STAT547!

**Comment by vincenzocoia** [comment]
Really glad to hear the course was useful! Thanks for the feedback!

**Comment by lsloboda** [comment]
Agreed. There are already a few projects that I want to try these tools on. I feel like this course is going to be very useful for my future work!

**Comment by rasiimwe** [comment]
Totally agree. Thanks Dr. Coia and the entire STA545 teaching team. The course was awesome!!, nicely administered, practical and with lots of helful material. 👏 👏 👏  🏆.

**Comment by tsmith93** [comment]
As a new user of R and github, I don't think it would've been possible to get a better introduction. Thanks Vincenzo and all the TAs for your patience and enthusiasm throughout this course! It made the course very enjoyable. Looking forward to STAT 547M :o)

**Comment by aleurcelay** [comment]
I am new to R as well, and from this course I feel like I've learned lots and I know it will be useful for my future work. Thank you so much to the teaching team! Also looking forward to STAT547 😃

**Comment by Caroline-Seip** [comment]
I agree, this course was super helpful for getting me past the scary hurdle of starting R. A great introduction, looking forward to the next half 👏  Thanks Vincenzo and TAs!

**Comment by alorentzian** [comment]
I am also new to R and agree with all of the above comments! It was a great introduction and I learned a lot without feeling overwhelmed. Thanks for a great course!

**Comment by rning-wu** [comment]
Thanks Vincenzo! See you in 547!
