### ISSUE TITLE
[cm-013] Issues with ggplotly and plot_ly

### ISSUE THREAD

**Issue by ErnestL91** [STAT545-UBC/Discussion-Internal#48]
From the cm-013 lecture this Tuesday, the final parts of the in-class coding work involved using ggplotly and plot_ly. I seem to be having issues with running these two functions, with this error message showing up:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called ‘shiny’

I have the plotly and tidyverse library loaded already, so I thought about installing and loading the "shiny" package. However, when I tried installing "shiny" I get another error that stops the installation:

preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'httpuv' 1.4.1 is being loaded, but >= 1.4.3 is required
ERROR: lazy loading failed for package 'shiny'

removing 'C:/Users/ernest91/Documents/R/R-3.3.2/library/shiny'
Warning in install.packages :
  running command '"C:/Users/ernest91/DOCUME~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\ernest91\Documents\R\R-3.3.2\library" C:\Users\ernest91\AppData\Local\Temp\Rtmp67a1w7/downloaded_packages/shiny_1.1.0.tar.gz' had status 1

Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status

Any help would be appreciated, thank you!

**Comment by MaunishUBC** [comment]
Hi Ernest, 

I had a similar issue while installing plotly and it turned out the cause of the error was that I wasn't running the latest version of R.
Try updating R to version 3.5.1 and that should hopefully allow you to smoothly install plotly.

Cheers,
Maunish

**Comment by ErnestL91** [comment]
Thanks @MaunishUBC, that worked for me, cheers! :)
