### ISSUE TITLE
Working with big files using data.table()

### ISSUE THREAD

**Issue by Rashedul** [STAT545-UBC/Discussion-Internal#49]
If someone is working with big table, `data.table()` might be a good choice. I loaded a 2GB text file onto Rstudio using `data.table()` and `read.table()`. `data.table()` took 1.5 minutes whereas `read.table()` took 8 minutes on the same server. It has other operations similar to `dplyr` which might be faster as well.

"`data.table` inherits from `data.frame`. It offers fast and memory efficient: file reader and writer,
aggregations, updates, equi, non-equi, rolling, range and interval joins, in a short and flexible syntax,
for faster development"

https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html

**Comment by rgryba** [comment]
I've dabbled in data.table some but it's seemed less intuitive than dplyr. BUT it has this awesome rolling join function that lets you join based on closed dates/times.
