### ISSUE TITLE
Peer Review 4 Marking Error

### ISSUE THREAD

**Issue by j-schaub** [STAT545-UBC/Discussion-Internal#51]
Hi @STAT545-UBC/2018_teaching_team 

I submitted 2 peer reviews for Peer Review 4 but one of them was someone I had to choose randomly. I included links in my canvas submission, so I suspect that there was a grading error. Can one of the TA's please look into this?

Thanks!

**Comment by Caroline-Seip** [comment]
I had a similar error for both Peer Review 3 and 4. I also included links to both. I don't see anywhere explaining why I got 50% instead of 100%? Thanks!

**Comment by zhamadeh** [comment]
I also had the same problem and double checked both my peer reviews were submitted on time and to the right people. Thanks for looking into this!

**Comment by ChadFibke** [comment]
Hey,

I will look into this when I get to my desk!

**Comment by ChadFibke** [comment]
Hey @j-schaub, @Caroline-Seip , AND @zhamadeh 

I will give you feed back in canvas as a comment on your peer review.
