### ISSUE TITLE
FYI about auto-creating directories in repo (from cm102 in-class exercise).

### ISSUE THREAD

**Issue by schignel** [STAT545-UBC/Discussion-Internal#53]
Hi everyone, 

Just FYI: 

If you're trying to do the bonus task from today's in-class assignment and actually create the directories in your participation repo, I found that the code provided in the .Rmd works great, but you need to make sure to install the `here` package first. This worked for me:

`install.packages("here")
for (folder in folders) dir.create(here::here(folder))`

Cheers,
Steve

**Comment by schignel** [comment]
Just following up on the next step for this: did anyone get the for loop to create the READMEs to work? 

I run the following code and nothing seems to happen (no error but also no README files)

`for (i in 1:length(files)) write(contents[i], files[i])`

My working directory is set to my stat545_participation repo, where all of the cm1** folders were created. 

Any ideas?

**Comment by rgryba** [comment]
I had to modify the code so that the files actually had the entire path name. 

(files <- str_c(here::here(folders), "/READ.md"))
for (i in 1:length(files)) write(contents[i], files[i])

**Comment by aleurcelay** [comment]
Thanks @schignel and @rgryba the code worked for me! 👍
