### ISSUE TITLE
Automatically show html outputs in R Studio viewer?

### ISSUE THREAD

**Issue by schignel** [STAT545-UBC/Discussion-Internal#54]
Has anyone figured out which settings to change so that markdown outputs automatically appear in the R Studio viewer (like @vincenzocoia's does)?

I've looked around a bit and haven't found a solution yet...

Thanks!

**Comment by j-schaub** [comment]
This website has some general information on R Notebooks:
https://rmarkdown.rstudio.com/r_notebooks

It seems there is an option to specify printing traditionally (in console) instead of in the document. See section 'Creating a Notebook'. 

Hope this helps!

**Comment by rasiimwe** [comment]
##### Settings tab -> You can toggle between `chunk output inline` and `chunk output in console`


<img width="515" alt="screen shot 2018-10-25 at 1 10 59 pm" src="https://user-images.githubusercontent.com/24922257/47528504-386b1c00-d85a-11e8-9a54-e68ba9b3208b.png">

**Comment by rgryba** [comment]
Does the above also control if the output is shown in the knitted doc?

**Comment by rasiimwe** [comment]
The outupt will still be visible in the knitted doc even when you opt to view your code output through  the console.

**Comment by schignel** [comment]
Thanks very much everyone!
