### ISSUE TITLE
How to push newly created files/folders up to Github?

### ISSUE THREAD

**Issue by schignel** [STAT545-UBC/Discussion-Internal#55]
I'm probably missing something very obvious here, but I'm wondering how to push new folders/files created on my desktop repo to the Github repo. 

Also, how does syncing work in this case? For example, if I want to clean up my participation repo by putting files into different folders, should I do that on my desktop and push the changes, or should I do it on Github and pull them down? Is there a chance that doing this could break the links to my projects since it would change the file paths?

Thanks!

**Comment by j-schaub** [comment]
If the file/folder was created within your 'GitHub' folder on your desktop (i.e. the folder associated with your GitHub repo), it should appear as an item that you can check [x] and commit as you would any other file.

I have no information on syncing, but I can imagine it should work either way!

**Comment by zeeva85** [comment]
If it’s an empty folder it won’t show (I think). I normally make a folder with a readme locally then, stage, then commit, then push.

Staging is when you tick them, commit is when you commit and push is pushing onto GitHub.

**Comment by schignel** [comment]
Thanks @zeeva85, I just created the READMEs and commit/pushed and both the folders and READMEs are up on GitHub now. 

Thanks everyone!
