### ISSUE TITLE
Final Exercises from cm012

### ISSUE THREAD

**Issue by rachlobay** [STAT545-UBC/Discussion-Internal#58]
Hi. I was thinking it would be good to create a issue for the final exercises from cm012. So, if anyone has given the final exercises a try, it would be good to compare possible solutions here.

**Comment by rachlobay** [comment]
For example, I have tried:

Convert `words` to pig latin, which involves:

1. Make the first letter the last letter
    - Get the first letter with `str_sub(string, start, end)`.
2. Remove the first letter from `words`.
    - Hint: leave the `end` argument blank.
3. Add "ay" to the end of the word.
    - Use `str_c()`.

**Comment by rgryba** [comment]
Hi! I assumed it was converting all of the words in the 'words' object into piglatin :)

My approach:

words %>%
  str_c(., str_sub(., 1, 1)) %>%
  str_sub(start=2) %>%
  str_c(., "ay")

I've used "." to indicate that each function should be applied to all of the words.
