### ISSUE TITLE
Clarification of a few of the questions in HW06

### ISSUE THREAD

**Issue by rachlobay** [STAT545-UBC/Discussion-Internal#61]
Hi @STAT545-UBC/2018_teaching_team,

I have  a few questions on HW06:

1) If we choose the options to do the exercises from the [Strings chapter](https://r4ds.had.co.nz/strings.html) about how many exercises would you like us to do? There seems to be many to choose from. What exercises would you highly recommend to try (ie. what exercises are the most important or interesting, in your opinion)?

2) To clarify, if we choose the option to work through and write up a lesson from the purrr tutorial, are we supposed to extract the most important ideas from the lesson we choose and write out the lesson in our own way? So, in a way, it is sort of like a cheat sheet?

I appreciate any help 😄

**Comment by ChadFibke** [comment]
Hey @rachlobay,

Question 1:
Your assignment should be more about the quality than quantity.  I think it would be appropriate to introduce what strings are than go into manipulating them with 1 or 2 sections. A high quality report could, for example, show how Regex/stringr relate into all the data manipulation/visualization steps learned in STAT545 (For example str_wrp() can help with fix long axes labels). The most interesting exercise depends on many factors, so I can't give you a definitive answer. Attempt concepts that 1) You do not know very well and want to learn, or 2) concepts that you will use in your research.    

Question 2:
Yes you are right. We want you to focus on important topics in a concise way (applying these concepts to a diverse set of issues even), and essentially make a cheat sheet that future you and others can learn from.

I hope this helps,

Chad

**Comment by rachlobay** [comment]
Awesome. Thanks for letting me know 👍

**Comment by rachlobay** [comment]
Closed #61
