### ISSUE TITLE
hw06: Singer package not available for R 3.5.1

### ISSUE THREAD

**Issue by MielleM** [STAT545-UBC/Discussion-Internal#62]
When I try to install the singer package to work on option 4 of hw06, I get the following message: 

"Warning in install.packages :
  package ‘singer’ is not available (for R version 3.5.1)" 

Is there a workaround, or a different dataset that we can use to work on this option? I would really like to work with geographic data if possible. 

Thanks!

**Comment by zjbthomas** [comment]
Hi @MielleM , can you check [this](https://github.com/STAT545-UBC/Discussion-Internal/issues/60)? Thank you.

**Comment by MielleM** [comment]
Somehow missed that, thank you!
