### ISSUE TITLE
Problem with unnest() function in 547cm04 exercise

### ISSUE THREAD

**Issue by liuyadong08** [STAT545-UBC/Discussion-Internal#63]
Hi all,
When we were doing the class exercise yesterday, I ran into problem with the unnest() function. 
The code that I used was got_alias %>% drop_na() %>% unnest(), and I think it should be identical to the code typed by the instructor. However, R threw me an error saying "Error in stats::complete.cases(data) : invalid 'type' (list) of argument". 
Anyone knows what could be the problem?

**Comment by rasiimwe** [comment]
Hey @liuyadong08 
Could you check that you have the below lines prior to your ` got_alias %>% drop_na()....` line :

```r
got_alias <- got_chars %>% {
  tibble(name = map_chr(., "name"),
        aliases = map(., "aliases"))
}
got_alias

```
