### ISSUE TITLE
hw repository on git classroom?

### ISSUE THREAD

**Issue by rgryba** [STAT545-UBC/Discussion-Internal#64]
Hi,

I didn't take 545 and am a bit confused about the repository for hw in the git classroom. On the 'assignment' page it says that you will be prompted to make the repository in the git classroom - where exactly is the prompt? 

Thanks for any help!

**Comment by j-schaub** [comment]
We receive a prompt through our assignment page on Canvas (for non-UBC people, its our website that courses can use to give assignments, give our grades, etc...). To get the prompt, you need to be able to access Canvas, so you need to be enrolled in the course.

**Comment by rgryba** [comment]
Thanks!
