### ISSUE TITLE
Posted: Homeworkd 07

### ISSUE THREAD

**Issue by hsmohammed** [STAT545-UBC/Discussion-Internal#66]
@STAT545-UBC/2018_students cc @STAT545-UBC/2018_teaching_team

[Homework 07](http://stat545.com/Classroom/assignments/hw07/hw07.html) has been posted.

**Comment by vincenzocoia** [comment]
The deadline of Homework 07 is now extended by 48 hours.

**Comment by zeeva85** [comment]
15th November 11.59 pm ?

**Comment by yihaoz** [comment]
> 15th November 11.59 pm ?

yes
