### ISSUE TITLE
build_vignettes() issue

### ISSUE THREAD

**Issue by tsmith93** [STAT545-UBC/Discussion-Internal#67]
Anybody encounter this before?

Anybody ever encounter this:

build_vignettes()
Building powers vignettes
<system_command_status_error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout), stderr_line_callback = real_callback(stderr), stdout_callback = real_block_callback, stderr_callback = real_block_callback, echo_cmd = echo, echo = show, spinner = spinner, error_on_status = fail_on_status, timeout = timeout): System command error>
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout), :
System command error

**Comment by rasiimwe** [comment]
Hey @tsmith93 
Try following [this](https://github.com/r-lib/devtools/issues/1688). Alternatively, it could be an issue with dependencies or R version.
