### ISSUE TITLE
Package documentation not working? 

### ISSUE THREAD

**Issue by rgryba** [STAT545-UBC/Discussion-Internal#69]
Hi,

I'm running through the in class stuff from today (computer issues during class). I run use_package_doc(), copied in the code, ran document() and load_all(). No errors or warnings show up.

When I try ?powers I get the following error:
No documentation for ‘powers’ in specified packages and libraries:
you could try ‘??powers’

Thoughts?

**Comment by rachlobay** [comment]
Try library(powers) and then ?powers. I had the same issue with dplyr when I didn't use library(dplyr) before ?dplyr. The error message for that was: No documentation for ‘dplyr’ in specified packages and libraries:
you could try ‘??dplyr’

Now, after doing that, when I typed ?powers, the R documentation that shows up looks like the DESCRIPTION file that we created in class. Check to see that you have a DESCRIPTION in the package folder. Also, one thing to check is the documentation for the functions we created in class is by using the help function. For example, help("square", package="powers") gives the documentation for the square function.

**Comment by rgryba** [comment]
Thanks @rachlobay - realized my actual issue was missing info in the 'header' in pow.
