### ISSUE TITLE
Relabel factor levels with a function?

### ISSUE THREAD

**Issue by schignel** [STAT545-UBC/Discussion-Internal#72]
Hi everyone, 

I sometimes have to work with messy data where there are typos and inconsistencies as a result of data entry errors, so for HW07, I want to write a function that will go through all of the factor levels and trim extra white space and convert to title case using `stringr`.

Here is some dummy data and the function I've got so far. It does what I want, except that I can't figure out the last step in order to rename the levels. I'm sure it's something obvious that I'm missing...any help would be appreciated! 

**Create a factor with "dirty" levels**
production <- factor(c("  HIGH production", "MED production  ",  "MED production  ", " low Production", "  HIGH production"))
production

**Create a function to clean the levels**
fclean <- function(x) {
  xtrim <- stringr::str_to_title(x)
  xtrim.tit <- stringr::str_trim(xtrim)
  xtrim.tit
}

fclean(production)

**Comment by vincenzocoia** [comment]
It might be better to use the `forcats` package, such as `fct_relabel()`, and use `stringr` functions within a `forcats` function.

**Comment by schignel** [comment]
Thanks @vincenzocoia, and sorry for the delayed reply--I must have missed the email update for this thread a couple of days ago!  @YuHsiangLo helped me out with this after class (thanks!)--it turns out I just needed to wrap the last line in as.factor(). I'll definitely look into `fct_relabel()` for next time though...
