### ISSUE TITLE
HW07 Question - Modify instructions telling someone how to download the package

### ISSUE THREAD

**Issue by rachlobay** [STAT545-UBC/Discussion-Internal#74]
@STAT545-UBC/2018_teaching_team

A couple classmates and I had this question and I just wanted to confirm what was meant by modifying the instructions to tell someone how to download the package. Does that just refer to modifying the README.Rmd instructions on installation?

I thought that was all there was to it. So, I did the following, which seems to work.

You can install my version of the powers package from github from:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("STAT545-UBC-students/hw07-rachlobay/powers-master")
```

Thanks for any help!

**Comment by vincenzocoia** [comment]
Works for me!

**Comment by rachlobay** [comment]
Cool. Thanks!
