### ISSUE TITLE
`*-package.R` is not created when using `devtools::create()` or `rstudio>new project>r package`

### ISSUE THREAD

**Issue by zeeva85** [STAT545-UBC/Discussion-Internal#76]
how did you guys get the` *-package.R`  file in the `./R` folde r after creating a package ?. Did you manually create it ? or was it created automatically, I can't seems to get it to make it automatically, been trying for a while. 

<img width="418" alt="screen shot 2018-11-14 at 12 49 30 pm" src="https://user-images.githubusercontent.com/35077731/48511620-14bd4500-e80c-11e8-88b3-5f57a99e8fc9.png">

@vincenzocoia 
Thank you

**Comment by MielleM** [comment]
Check section [8.1](http://stat545.com/Classroom/notes/cm105.nb.html) of the class instructions. 

Execute: `use_package_doc()` and then `document()` in the console. Might need to add `library(devtools)` before `document`, if you've restarted R since last using devtools.

**Comment by ChadFibke** [comment]
Thank @MielleM,

@zeeva85 make sure that both roxygen2 and devtools are downloaded. Once you use the document function, this package.R file should be automatically created.

**Comment by zeeva85** [comment]
Hey chad

**Comment by zeeva85** [comment]
Thank you @MielleM. It Works.
