### ISSUE TITLE
Making Folders in Repos

### ISSUE THREAD

**Issue by JasmineLib** [STAT545-UBC/Discussion-Internal#8]
Hi all! I had some trouble figuring out how to make a folder in my participation Repo. It's actually super easy! 
Here is a link explaining how: 

https://github.com/KirstieJane/STEMMRoleModels/wiki/Creating-new-folders-in-GitHub-repository-via-the-browser

Jasmine

**Comment by rasiimwe** [comment]
Thanks Jasmine for your helpful post 👍. 

@vincenzocoia 

In line with the above post, now that we are creating new directories for our class participation repo and moving files around, do the file creation dates on the files matter at this point? For example, I pulled and pushed my "STAT545_participation" directory to to help me locally move the first files we created in the "stat545_md_explorer" into the new  "STAT545_participation/cm002" directory and it now seems as though the files were created today :smile: 

Is there an alternative way of easily moving files from one directory to another on GitHub to maintain the original state of the files?

Thanks

**Comment by alvin-q** [comment]
Hi @rasiimwe ,
Yes, you can just rename a file.
Ex. rename STAT545_participation/README.md to STAT545_participation/cm02/README.md
And this would just "move" the file into that folder.

**Comment by MielleM** [comment]
Thanks for posting, @JasmineLib! I can always re-upload it, but does anyone if there is a way to move pdfs? The method above doesn't seem to be available for pdfs.

**Comment by vincenzocoia** [comment]
> do the file creation dates on the files matter at this point?

Everything will still be in your commit history, so no need to worry! Plus, we'll be lenient in the first two weeks, as some students will be joining us late.
