### ISSUE TITLE
HW08: Starter code didn't show up in new repo

### ISSUE THREAD

**Issue by patriciata** [STAT545-UBC/Discussion-Internal#81]
Accepting the assignment allegedly created a new repository and imported some starter code, but I can't seem to see the starter code in my Homework 8 repo.

What is the starter code supposed to look like?

**Comment by rasiimwe** [comment]
@patriciata 
Your inquiry could have been addressed in issue #78 .

**Comment by patriciata** [comment]
Thanks!

(https://github.com/STAT545-UBC-students/hw08-seed is where to find it if anyone else is wondering.)
