### ISSUE TITLE
Rubric Issues

### ISSUE THREAD

**Issue by j-schaub** [STAT545-UBC/Discussion-Internal#83]
Hi @STAT545-UBC/2018_teaching_team 

Since changing the cutoff for 3/3 to be a 90% or higher on our homework, I don't think anyone has updated the rubric that is used for the homework. The third slot still says 100.0-80.0 on canvas, and I think this was also reflected in my mark for homework 6 (i.e. I got a 3/3 in one of the sections and got 85/100 points).

Am I misinterpreting something?

**Comment by rasiimwe** [comment]
@j-schaub 
Thanks for pointing this out. I too had a similar scenario on my homework 6. Could we kindly get clarity on the grading used.

**Comment by liuyadong08** [comment]
Hi @j-schaub 
Thanks for this post! I am having a similar situation. It seems that the rubric that is used for the homework 06 is still the one for 545. If the teaching team could change the cutoff for further assignments, that will be great.

**Comment by ChadFibke** [comment]
Hey @j-schaub @liuyadong08 @rasiimwe,

Yes, we still need to update the grading rubric on canvas, but in the meantime the TAs are grading and placing students into a grade category. Once in a category, the TA can shift the grade down within that category ( say 100 -> 95) if they feel there can be improvement. These final grades are then entered into canvas, and arbitrarily placed into  into 1 of the 3 existing (out of date) grading categories. An 85% should technically be in the  "2" category, but our system places it in the "3" category. Does this clear things up? 

Chad

**Comment by j-schaub** [comment]
Yes, thank you for clarifying @ChadFibke 
I felt like the criteria for grading became less strict when Dr. Coia introduced the 90% cutoff, but I still feel like I am being marked quite strictly!

**Comment by MielleM** [comment]
@ChadFibke, can we get some clarification on how taking on more complex/difficult tasks for the assignments is reflected in marking? 

For example, I created a new package from scratch for hw07. It had some issues, but was functional and included the elements specified in the instructions as far as I understand-- but I did worse on that assignment than others where I was less ambitious. Does the execution have to be excellent for completing harder tasks to get a better mark?

**Comment by rgryba** [comment]
Hi - I actually have the same scenario :) Thanks for any clarification!

Cheers

**Comment by ChadFibke** [comment]
@MielleM,

Yes, completing the base task should afford you anywhere between 0-90%. In order to get the upper range this task has to be spot on with a little flare. Now, if you have an excellent base tasks with any attempt of the challenge section you mark will range from 90-100%. The effort you put into the wow factor will be correlated with your mark between 90-100%. 

However I think for next year we will have to be more clear with the wow factor because, as of now, it is not an exact science. Completing the task and wow factor doesn't guarantee you over 90%. Many errors can be carried through both the task, and wow factor, and at this point completing the wow factor will add nominal marks to your assignment. The @STAT545-UBC/2018_teaching_team will have to sit down at the end and iron out the wrinkles for next year, so that the amount of marks afforded to the wow factors are more clear.   

So I looked into both of your cases and @Rashedul was responsible for marking your HW07 assignments. @Rashedul are you able to give the students more concise feedback on how they lost specific marks?

**Comment by ChadFibke** [comment]
@MielleM @rgryba ,

I'm sorry if things seem to be inconsistent! We are working on it!

**Comment by rgryba** [comment]
Marking code and output is no exact science! I really appreciate you looking at it and any additional feedback.

**Comment by funkedavid82** [comment]
@Rashedul, @ChadFibke,  
I am not sure I got you right. My homework7 grade was not reflecting my work and even the Wow! options that I did. I thought the grading error was already fixed but got my homework7 a few minutes ago and still found an unfair grade. When exactly will this be fixed so as to decide on homework10. @Rashedul is it possible to have more feedback please?

**Comment by Rashedul** [comment]
@MielleM , @funkedavid82 , @rgryba 

Yes, I can revise the grade tonight. Lets continue the discussion on my grading on hw07 at `TA comment` thread. I already put some `?` or, `!` marks  or, `NOTE ` on my comments for further clarification from you. I appreciate about your response.

Thanks!

**Comment by MielleM** [comment]
Thank you @Rashedul!  I've commented on your Issue in my homework repo.

**Comment by MielleM** [comment]
@ChadFibke, @Rashedul 

total agree with @rgryba -- code is a really hard thing to mark consistently, appreciate the extra help understanding our feedback.

**Comment by zeeva85** [comment]
@ChadFibke 
> The @STAT545-UBC/2018_teaching_team will have to sit down at the end and iron out the wrinkles for next year, so that the amount of marks afforded to the wow factors are more clear.

Just a suggestion for next year, I myself sometimes thought I did really well until I peer reviewed or look at other submission and realized there are really excellent work out there and it wouldn't be fair for those who actually did better than me to get the same grades as me. 

Finding that balance in grading students without being unfair to people who actually did the base work as well as nailing the wow factors gracefully is a very subjective matter amongst individual. 

As such my only suggestion would be, one TA would be assigned ONE Homework to grade to reduce the grading bias as each TA has different views in regards to this balance as well as actually getting to see the submission of the whole class before assigning grades to them individually eliminating any need for disparity and dispute.

**Comment by funkedavid82** [comment]
@Rashedul,
You commented that you couldn't run my code and then put 80%? Whereas, i got a peer-reviewed comment on the same homework7. Thanks for your time and understanding.

**Comment by iyaniwura** [comment]
@Rashedul 

I need some clarifications please. I thought the last column in the rubric is for > 90%, why do I still have a grade lower than 90% when I am in  this category?

**Comment by rachlobay** [comment]
I'm a little late... but I have a couple thoughts based on reading @zeeva85’s post on how grading could work for future iterations of the course. I think that his view that one TA would be assigned to grade one student to reduce bias could work. A few of the benefits that I see are that the TA would have a better idea of how each student is progressing as work through assignments. So, the TA would be able to gauge if their students are putting more effort into going above and beyond in assignments.

**Comment by vincenzocoia** [comment]
> As such my only suggestion would be, one TA would be assigned ONE Homework to grade to reduce the grading bias

Having one TA grade all of Assignment X would also allow us to tailor TA expertise to corresponding assignments. A big downfall with this method, though, is that the turnaround time for grading would be quite high.

> one TA would be assigned to grade one student to reduce bias could work

I'd be concerned for the students who get assigned to the strictest grader.

I spoke with the teaching team yesterday, and we came up with an idea that might work well: 

1. assignments to be made with clearer instructions of expectations, with less generic rubrics, and
2. as part of the workflow for grading, keep a global "grading guide" page that graders add to, refer to, and discuss.

**Comment by rachlobay** [comment]
Thanks for the update on what you are planning to try for grading. That plan sounds good :thumbsup:
