### ISSUE TITLE
Changing server code to show all countries when no country selection is made

### ISSUE THREAD

**Issue by MielleM** [STAT545-UBC/Discussion-Internal#84]
I'm working on the last prompt in hw08: Provide a way for the user to show results from all countries. I've done this by adding a "filter by country" button that only shows the option to select a country when checked-- my issue is that now, of course, my plot/table won't show up unless a country is selected. 

I'm having trouble changing my server code so that all countries show up when no country selection is made. It seems like the `filtered()` function might be the issue? I'm having trouble figuring out what to replace `NULL` with.

` filtered <- reactive({
    if (is.null(input$countryInput)) {
      return(NULL)
    }
`
 
Not sure if I'm totally going in the wrong direction with this, any guidance appreciated.

**Comment by rgryba** [comment]
Hey! 

Your above code should work (as long as it's linked to the right wiget input) but you also need to place it in your ui as well.

**Comment by j-schaub** [comment]
Hi @MielleM ,

I couldn't get mine to work, but you have to insert an `if` statement in the server to filter only if the checkbox evaluates to TRUE. I'm still working on it, but the raw code in Dean's full version of the app has some examples of using the `if` statement. Hope that helps!

**Comment by fjbasedow** [comment]
Hi @MielleM,

You could try an if statement in the `filtered` part, where you filter for Country, Price, and Type if the country checkbox is checked and only for Price and Type if it isn't checked.

Cheers,
Rike
