### ISSUE TITLE
Hw08- App not deploying

### ISSUE THREAD

**Issue by funkedavid82** [STAT545-UBC/Discussion-Internal#87]
I am wondering if anyone have experienced this before. My app was fine until when i tried to deploy, I have this error now and the app won't even run:

Warning: Error in filter_impl: Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead. 

I need help please

**Comment by rgryba** [comment]
I didn't have the same error but mine wouldn't deploy until I actually put in the link to the folder where then app file lived. Maybe that will help?

**Comment by bassamjaved** [comment]
May or may not be helpful in your case, but make sure all library() calls
are present in your app.R

It's easy to forget these when programming interactively with the console.

**Comment by funkedavid82** [comment]
I figured out the problem. Since none of my previous code ran, I then concluded that the problem has to do with my RStudio. I think it crashed, but finally deployed from a friend's laptop.
