### ISSUE TITLE
Error during "Clean and Rebuild"

### ISSUE THREAD

**Issue by schignel** [STAT545-UBC/Discussion-Internal#92]
Hello, 

I'm just wondering if anyone else gets this error when pressing "Clean and Rebuild."

```
process_begin: CreateProcess(NULL, rm -f words.txt histogram.tsv histogram.png report.md report.html hist_vowels.tsv hist_vowels.png report2.md report2.html Rplots.pdf, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [clean] Error 2

```
It doesn't seem to affect the output, and there's no issue when I press "Build All" or run "make" in the terminal. Any thoughts?

Thanks!
Steve

**Comment by fjbasedow** [comment]
Hi Steve,

I had the same error and the problem was that I saved my .tsv file in the wrong folder. Check your directory specifications and make sure that your .tsv files are saved in the same folder as your Makefile.

Cheers,
Rike

**Comment by ChadFibke** [comment]
Hey @schignel,

Double check the spelling, and yes as @fjbasedow said you may not have the files in the directory that holds the Makefile. 

Chad

**Comment by schignel** [comment]
Thanks @fjbasedow and @ChadFibke, 

From what I can tell, everything is in the same folder and I don't have any typos. I know I'm probably just missing something obvious...

Here is the makefile code: 

`all: report.html report2.html

clean:
	rm -f words.txt histogram.tsv histogram.png report.md report.html hist_vowels.tsv hist_vowels.png report2.md report2.html

report2.html: report2.rmd hist_vowels.tsv hist_vowels.png
	Rscript -e 'rmarkdown::render("$<")'

report.html: report.rmd histogram.tsv histogram.png
	Rscript -e 'rmarkdown::render("$<")'
	
hist_vowels.png: hist_vowels.tsv
	Rscript -e 'library(ggplot2); qplot(Vowels, Freq, data=read.delim("$<")); ggsave("$@")'
	rm Rplots.pdf
	
histogram.png: histogram.tsv
	Rscript -e 'library(ggplot2); qplot(Length, Freq, data=read.delim("$<")); ggsave("$@")'
	rm Rplots.pdf

hist_vowels.tsv: hist_vowels.r words.txt
	Rscript $<
	
histogram.tsv: histogram.r words.txt
	Rscript $<

#words.txt: /usr/share/dict/words
	#cp $< $@

words.txt:
	Rscript -e 'download.file("http://svnweb.freebsd.org/base/head/share/dict/web2?view=co", destfile = "words.txt", quiet = TRUE)'
`

**Comment by ChadFibke** [comment]
@schignel ,

Do all of your commands have a tab , and do all targets show up as blue in your Make file? 

Go to R studio > Tools > Global options > Code 

Make sure the insert space for tabs is unchecked. You might be clicking tab, but r will insert spaces if the insert spaces for tabs is checked (something that you do not want). Just checking the simple things first before we have a deeper dive!

**Comment by schignel** [comment]
Thanks for the quick reply @ChadFibke! I just unchecked the option in "Global options" and believe I have the spacing correct. Still the same error though. Here's a screenshot:

![image](https://user-images.githubusercontent.com/19474876/49119457-41864900-f25d-11e8-8ee8-128b9d5b1eb9.png)

**Comment by ChadFibke** [comment]
@schignel ,

Are you on mac or windows?

**Comment by schignel** [comment]
@ChadFibke  I'm on Windows 7.

**Comment by ChadFibke** [comment]
@schignel,

Ah, look [Here](https://github.com/STAT545-UBC/Discussion/issues/55)

**Comment by schignel** [comment]
I can keep clicking through "Build All" and it makes the outputs, but it also throws the error 2. It just switches which file it can't find:

process_begin: CreateProcess(NULL, rm Rplots.pdf, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [hist_vowels.png] Error 2

Exited with status 2.

**Comment by ChadFibke** [comment]
Oh make sure to replace all your rm with del. I see there are still rm in your hist_vowels.png and histogram.png instructions. I think its the same problem different location. Let me know if that works.

**Comment by schignel** [comment]
Ah of course! Thanks so much @ChadFibke!
