### ISSUE TITLE
Errors when using terminal

### ISSUE THREAD

**Issue by aleurcelay** [STAT545-UBC/Discussion-Internal#93]
Hi all,

My Makefile is perfectly running when I use Rstudio but when using the Terminal and I try to run `clean` I get:
 -bash: clean: command not found

Also, if I clean in Rstudio and then run `make` in the terminal I get: 

Rscript -e 'rmarkdown::render("report.rmd")'
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
Execution halted
make: *** [report.html] Error 1

I appreciate any suggestions, thanks!

**Comment by ChadFibke** [comment]
Hey,

Clean is a target name not a bash/terminal command, so that is why you are getting that first error.Navigate to your makefile directory in the terminal and put

make clean 

For the second issue make sure all of your real target names are associated with the all phoney target 

all: target1 target2 etc 


Then run the following command in terminal:


make all

That should do it.

Cheers,
Chad

**Comment by aleurcelay** [comment]
Hi @ChadFibke thanks for your quick reply!
Of course, I was using clean wrong, I fixed that. 

But I still cannot fix the make all issue. It only happens if I use the terminal outside RStudio, when I use the RStudio terminal it's all fine. I checked, and all my target names are in all: 

Do you have any other suggestions for this?

Thank you so much!

**Comment by ChadFibke** [comment]
@aleurcelay,

One problem solved ⭐️ 

Oh ok that sounds like an easy fix. So when you open the terminal in R it places you in the working directory where your project and Make file are. HOWEVER if you just open terminal from your mac it places you in your home directory `/Users/chadfibke` for me. This directory will not have your Make file and your command make all will not work. 
Open the R studio project that contains the Makefile and type in `getwd()` This will print an absolute pathway to that directory (will look something like /Users/chadfibke/Desktop/STAT545/HW08 )> Copy that  pathway > Now open up your terminal outside of r and put:

```
cd /Users/chadfibke/Desktop/STAT545/HW08

# This tells the compute to change from you home location to the location of the folder that is holeing the Make file
```
Then make sure you are in the right directory using the command 

```
ls
# This will print "LiSt" all the files in your working directory. All these files you see in your Rstudio make folder should appear 
```
Then run the command 

```
make all
```

Cheers,
Chad

**Comment by aleurcelay** [comment]
@ChadFibke I am in my homework directory but it still throws the error. I read it is related to pandoc in knit but I still don't know how to fix this.

**Comment by Sukeysun** [comment]
@ChadFibke ， I think your problem is similar to problem:[Error: pandoc version 1.12.3 or higher is required and was not found #86 ](https://github.com/STAT545-UBC/Discussion-Internal/issues/86)

**Comment by zeeva85** [comment]
#86, it worked for me after a few days without doing anything to it, but in between those days i did do a homebrew installation. Not sure if it updates the pandoc in the process. 

Try doing `rmarkdown::pandoc_version()` in R studio
