### ISSUE TITLE
Forgot to run makefile before pushing to Github

### ISSUE THREAD

**Issue by iyaniwura** [STAT545-UBC/Discussion-Internal#94]
@vincenzocoia @ChadFibke @hsmohammed @Rashedul @sherrie9 

I just noticed that I did not run my Makefile before pushing my homework 9 to Github. As a result of this the output generated by the Makefile is not displaying in the uploaded assignment. Is it okay if I run the Makefile now and push again?

I already submitted the assignment last night before deadline and all the codes are there. The only problem is that there are no outputs.

Here is a link to my homework repo for confirmation:

https://github.com/STAT545-UBC-students/hw09-iyaniwura

**Comment by ChadFibke** [comment]
Hey @iyaniwura,

Sorry for the late reply. Your output is not needed if your Makefile has no errors. @sherrie9 is responsible for marking your HW09, so she should be able to run your makefile from her laptop to generate your output. 

Cheers,
Chad
