### ISSUE TITLE
Missing homework Grades?!?

### ISSUE THREAD

**Issue by ChadFibke** [STAT545-UBC/Discussion-Internal#96]
Hey @STAT545-UBC/2018_teaching_team & @STAT545-UBC/2018_students ,

If you have a grade for HW06 and HW08, but do not have a grade for HW07 (or missing any combination) do not panic. TA's are responsible for marking different groups of students each assignment, and some of the TAs are still playing catch up. **So, your missing mark is our fault, not yours**. The TAs have spoken about this and plan to catch up on the marking, and should have your marks for HW07, HW08 posted ASAP. If you have an questions please contact one of the teaching staff. 

Cheers,
Chad

**Comment by daattali** [comment]
I think tagging the 2014 students was a typo

**Comment by ChadFibke** [comment]
Oh my Lanta... yes it was
