### ISSUE TITLE
Thanks for the great course!

### ISSUE THREAD

**Issue by MalcolmNSB** [STAT545-UBC/Discussion-Internal#98]
Thanks @vincenzocoia and  @STAT545-UBC/2018_teaching_team  for a really fun course! I had no experience in R or data analysis prior to taking Stat545/547, and I thoroughly enjoyed learning all these topics in both courses.

3 months ago I would not have had a clue about things like API requests, and now it all sounds really cool! 

Cheers!

**Comment by zeeva85** [comment]
Likewise thank you vincen, TA’s and to all the fellow peer reviewers. 

Learned so much from everyone experiences and suggestions.

**Comment by rachlobay** [comment]
Yes. I agree. The course has been a great learning experience. I think that material that we learned here will definitely be applicable to future projects.

**Comment by g-ziyan** [comment]
Strongly agreed! It is impressed how many things could be done in R. Thanks very much to teaching team! 👍

**Comment by rning-wu** [comment]
Thanks for the great course!

**Comment by curtis77** [comment]
Thanks to Vincenzo and the TA's! The course was great!

**Comment by yihaoz** [comment]
Agreed! The course content is useful and the course is very well organized as well! Thanks to the teaching team

**Comment by Irissq28** [comment]
Many thanks to Vincenzo and the teaching team! I learned a lot from this awesome course, the course material is every useful!

**Comment by chenchenguo** [comment]
Thanks to Vincen for excellent and patient teaching~ Learn a lot from this course

**Comment by rasiimwe** [comment]
This was a great and fulfilling course!!! I am already applying the concepts learned in my research!!  Thank you @vincenzocoia for the great and informative lectures. The resources were numerous and very handy, for future reference too. The administration was impeccable!

@vincenzocoia, @Rashedul, @sherrie9, @hsmohammed, @ChadFibke 
Many thanks

**Comment by MielleM** [comment]
Agreed, this course helped me build programming skills SO much!

**Comment by vincenzocoia** [comment]
This is all really great to hear! Thank you for the kind words. 🎆

**Comment by schignel** [comment]
Yes, thanks @vincenzocoia and @STAT545-UBC/2018_teaching_team! It's incredible to think about how much I've learned and improved in the last 3 months and I'm excited to keep learning more.

**Comment by aleurcelay** [comment]
Thanks so much @STAT545-UBC/2018_teaching_team ! This course was super useful, I am impressed that I learned so much in just five weeks!
